### ISSUE TITLE
Error when saving project

### ISSUE THREAD

**Issue by certrik** [AccentuSoft/LinkScope_Client#26]
```
[2023-07-14 12:23:09,466] - INFO: Starting LinkScope Client, Version v1.5.1
[2023-07-14 12:23:09,536] - INFO: Creating new Local Entities Database.
[2023-07-14 12:23:10,559] - INFO: Created new Tab Notes file.
[2023-07-14 12:23:10,563] - INFO: Project opened, ready to work.
[2023-07-14 12:23:15,222] - ERROR: Could not Save Project: AssertionError()
Traceback (most recent call last):
  File "C:\1_Work\LINKSC~1\LINKSC~1\LinkScope.py", line 129, in saveProject
  File "C:\1_Work\LINKSC~1\LINKSC~1\LinkScope.py", line 122, in saveHelper
  File "C:\1_Work\LINKSC~1\LINKSC~1\Core\SettingsObject.py", line 117, in save
  File "C:\1_Work\LINKSC~1\LINKSC~1\Core\PathHelper.py", line 131, in is_path_exists_or_creatable_portable
  File "C:\1_Work\LINKSC~1\LINKSC~1\Core\PathHelper.py", line 49, in is_pathname_valid
AssertionError
[2023-07-14 12:25:01,144] - INFO: Failed Saving Project Test7
```

It seems that it can not handle directory paths that are longer than 8 characters.

**Comment by AccentuSoft** [comment]
It can, the issue is elsewhere:
https://github.com/AccentuSoft/LinkScope_Client/blob/cdcf83ea27e8bd0e4a76caf8805630f2468d4115/Core/PathHelper.py#L49

Could you please check that the environment variable 'HOMEDRIVE' is set to a writeable directory?

**Comment by AccentuSoft** [comment]
Was this issue resolved?
